In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df  = pd.read_csv('train.csv')
df

,id,Date,Count,Hour,Hotness,Humidity,Wind Speed,Visibility,Solar Radiation,Rainfall,Snowfall,Seasons,Holiday,Working Day
0,1,05/08/2018,222,6:00,300.3,83,5.04,1080,0.00,0.0,0.0,Summer,NO,YES
1,2,21/01/2018,170,23:00,272.6,32,2.16,2000,0.00,0.0,0.0,Winter,NO,YES
2,3,11/05/2018,486,6:00,285.0,83,1.44,321,0.01,0.0,0.0,Spring,NO,YES
3,4,05/07/2018,929,13:00,301.1,67,3.96,1772,1.43,0.0,0.0,Summer,NO,YES
4,5,02/01/2018,58,5:00,269.9,67,2.16,1384,0.00,0.0,0.0,Winter,NO,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,4982,21/07/2018,1423,19:00,306.4,51,9.36,2000,0.59,0.0,0.0,Summer,NO,YES
4982,4983,19/03/2018,818,19:00,281.4,51,11.88,1977,0.01,0.0,0.0,Spring,NO,YES
4983,4984,03/10/2018,1849,13:00,295.5,40,9.36,1854,2.64,0.0,0.0,Autumn,YES,YES
4984,4985,09/01/2018,281,21:00,268.2,59,3.24,2000,0.00,0.0,0.0,Winter,NO,YES
4985,4986,30/05/2018,1119,14:00,297.3,58,10.44,1211,2.92,0.0,0.0,Spring,NO,YES

In [3]:
seasons=['Summer', 'Winter', 'Spring', 'Autumn']
list1=  []
for i in range(0, 4986):
  list1.append(0)

df['Summer'] = list1
df['Winter']  = list1
df['Spring'] = list1
df['Autumn'] =list1

for label in seasons:
  df[label] = np.where(df['Seasons']==label,1,0)
  df[['Seasons']+seasons]
  
df = df.drop('Seasons', axis=1)

In [4]:
from sklearn.preprocessing import LabelEncoder
object_cols=['Holiday','Working Day']

In [5]:
from sklearn.preprocessing import LabelEncoder
object_cols=['Holiday','Working Day']
label_encoder = LabelEncoder()
for col in set(object_cols):
    df[col] = label_encoder.fit_transform(df[col])
df['Hour']=df['Hour'].str.replace(":","")
df['Hour']=df['Hour'].astype(int)
df['Hour'] = df['Hour'].div(100)

In [11]:
df

,id,Date,Count,Hour,Hotness,Humidity,Wind Speed,Visibility,Solar Radiation,Rainfall,Snowfall,Holiday,Working Day,Summer,Winter,Spring,Autumn
0,1,05/08/2018,222,6.0,300.3,83,5.04,1080,0.00,0.0,0.0,0,1,1,0,0,0
1,2,21/01/2018,170,23.0,272.6,32,2.16,2000,0.00,0.0,0.0,0,1,0,1,0,0
2,3,11/05/2018,486,6.0,285.0,83,1.44,321,0.01,0.0,0.0,0,1,0,0,1,0
3,4,05/07/2018,929,13.0,301.1,67,3.96,1772,1.43,0.0,0.0,0,1,1,0,0,0
4,5,02/01/2018,58,5.0,269.9,67,2.16,1384,0.00,0.0,0.0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,4982,21/07/2018,1423,19.0,306.4,51,9.36,2000,0.59,0.0,0.0,0,1,1,0,0,0
4982,4983,19/03/2018,818,19.0,281.4,51,11.88,1977,0.01,0.0,0.0,0,1,0,0,1,0
4983,4984,03/10/2018,1849,13.0,295.5,40,9.36,1854,2.64,0.0,0.0,1,1,0,0,0,1
4984,4985,09/01/2018,281,21.0,268.2,59,3.24,2000,0.00,0.0,0.0,0,1,0,1,0,0
4985,4986,30/05/2018,1119,14.0,297.3,58,10.44,1211,2.92,0.0,0.0,0,1,0,0,1,0

In [13]:
a=  []
for i in range(0, 4986):
  a.append(0)
df['Month'] = a
df['Date1'] = a
df['Week'] = a
df['Weekday'] = a
df['Year'] = a
weekd = np.array([0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334])
for i in range(0, 4986):
  df['Month'][i] = int(df['Date'][i].split('/')[1])
  df['Date1'][i] =  int(df['Date'][i].split('/')[0])
  df['Week'][i] = int(df['Date'][i].split('/')[0])/7
  df['Weekday'][i] = ( weekd[int(df['Date'][i].split('/')[1]) -1] + int(df['Date'][i].split('/')[0]) )%7
  df['Year'][i] = (int(df['Date'][i].split('/')[2]))%100

C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\2614370238.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'][i] = int(df['Date'][i].split('/')[1])
C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\2614370238.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date1'][i] =  int(df['Date'][i].split('/')[0])
C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\2614370238.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Week'][i] = int(df['Date'][i].split('/')[0])/7
C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\2614370238.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Weekday'][i] = ( weekd[int(df['Date'][i].split('/')[1]) -1] + int(df['Date'][i].split('/')[0]) )%7
C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\2614370238.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'][i] = (int(df['Date'][i].split('/')[2]))%100

In [14]:
df = df.drop(['id','Date','Hour'], axis=1)

In [15]:
df.corr()

,Count,Hotness,Humidity,Wind Speed,Visibility,Solar Radiation,Rainfall,Snowfall,Holiday,Working Day,Summer,Winter,Spring,Autumn,Month,Date1,Week,Weekday,Year
Count,1.000000,0.530973,-0.209369,0.137468,0.211409,0.274194,-0.130910,-0.137735,-0.078455,0.198835,0.278500,-0.421405,0.020489,0.117243,0.139190,0.022701,0.022701,0.030222,0.213957
Hotness,0.530973,1.000000,0.152513,-0.037907,0.040110,0.359399,0.051681,-0.211947,-0.062517,-0.050046,0.663296,-0.733518,0.006468,0.056321,0.215036,0.017046,0.017046,-0.013316,0.372369
Humidity,-0.209369,0.152513,1.000000,-0.340127,-0.539017,-0.470769,0.248558,0.101478,-0.041381,-0.020022,0.184200,-0.226813,0.014180,0.025905,0.146164,-0.033928,-0.033928,-0.018425,0.016819
Wind Speed,0.137468,-0.037907,-0.340127,1.000000,0.176824,0.323715,-0.029477,-0.005662,0.016207,0.009973,-0.059899,0.111997,0.068206,-0.119197,-0.147014,-0.017187,-0.017187,0.063713,-0.008225
Visibility,0.211409,0.040110,-0.539017,0.176824,1.000000,0.152056,-0.186905,-0.124059,0.027235,-0.015761,0.073928,-0.000828,-0.202560,0.131079,0.063849,-0.102762,-0.102762,0.025924,0.076450
Solar Radiation,0.274194,0.359399,-0.470769,0.323715,0.152056,1.000000,-0.078339,-0.067572,-0.017851,-0.002442,0.129663,-0.179754,0.084425,-0.036845,-0.036550,0.004628,0.004628,0.024402,0.130522
Rainfall,-0.130910,0.051681,0.248558,-0.029477,-0.186905,-0.078339,1.000000,-0.004632,-0.007477,0.010708,0.064855,-0.060735,0.019449,-0.024202,0.011632,0.002479,0.002479,-0.009198,0.021403
Snowfall,-0.137735,-0.211947,0.101478,-0.005662,-0.124059,-0.067572,-0.004632,1.000000,-0.005841,0.030246,-0.095317,0.227392,-0.097881,-0.030517,0.069662,0.085816,0.085816,0.022299,-0.230637
Holiday,-0.078455,-0.062517,-0.041381,0.016207,0.027235,-0.017851,-0.007477,-0.005841,1.000000,-0.023423,-0.080992,0.119587,-0.044232,0.007288,0.052229,0.006040,0.006040,-0.025829,-0.136336
Working Day,0.198835,-0.050046,-0.020022,0.009973,-0.015761,-0.002442,0.010708,0.030246,-0.023423,1.000000,0.104478,0.102566,0.039641,-0.244287,-0.133657,0.088822,0.088822,-0.020960,-0.055080
Summer,0.278500,0.663296,0.184200,-0.059899,0.073928,0.129663,0.064855,-0.095317,-0.080992,0.104478,1.000000,-0.323220,-0.338105,-0.334561,0.079098,0.033942,0.033942,-0.003683,0.173574
Winter,-0.421405,-0.733518,-0.226813,0.111997,-0.000828,-0.179754,-0.060735,0.227392,0.119587,0.102566,-0.323220,1.000000,-0.331918,-0.328438,-0.230953,-0.012417,-0.012417,-0.004570,-0.537015
Spring,0.020489,0.006468,0.014180,0.068206,-0.202560,0.084425,0.019449,-0.097881,-0.044232,0.039641,-0.338105,-0.331918,1.000000,-0.343564,-0.435928,0.003626,0.003626,0.005006,0.178245
Autumn,0.117243,0.056321,0.025905,-0.119197,0.131079,-0.036845,-0.024202,-0.030517,0.007288,-0.244287,-0.334561,-0.328438,-0.343564,1.000000,0.586671,-0.025115,-0.025115,0.003113,0.176376
Month,0.139190,0.215036,0.146164,-0.147014,0.063849,-0.036550,0.011632,0.069662,0.052229,-0.133657,0.079098,-0.230953,-0.435928,0.586671,1.000000,0.001837,0.001837,-0.007860,-0.479289
Date1,0.022701,0.017046,-0.033928,-0.017187,-0.102762,0.004628,0.002479,0.085816,0.006040,0.088822,0.033942,-0.012417,0.003626,-0.025115,0.001837,1.000000,1.000000,0.013679,-0.007784
Week,0.022701,0.017046,-0.033928,-0.017187,-0.102762,0.004628,0.002479,0.085816,0.006040,0.088822,0.033942,-0.012417,0.003626,-0.025115,0.001837,1.000000,1.000000,0.013679,-0.007784
Weekday,0.030222,-0.013316,-0.018425,0.063713,0.025924,0.024402,-0.009198,0.022299,-0.025829,-0.020960,-0.003683,-0.004570,0.005006,0.003113,-0.007860,0.013679,0.013679,1.000000,0.012163
Year,0.213957,0.372369,0.016819,-0.008225,0.076450,0.130522,0.021403,-0.230637,-0.136336,-0.055080,0.173574,-0.537015,0.178245,0.176376,-0.479289,-0.007784,-0.007784,0.012163,1.000000

In [16]:
X = df.drop(['Count'], axis=1)
Y = df['Count']

In [17]:
X

,Hotness,Humidity,Wind Speed,Visibility,Solar Radiation,Rainfall,Snowfall,Holiday,Working Day,Summer,Winter,Spring,Autumn,Month,Date1,Week,Weekday,Year
0,300.3,83,5.04,1080,0.00,0.0,0.0,0,1,1,0,0,0,8,5,0.714286,0,18
1,272.6,32,2.16,2000,0.00,0.0,0.0,0,1,0,1,0,0,1,21,3.000000,0,18
2,285.0,83,1.44,321,0.01,0.0,0.0,0,1,0,0,1,0,5,11,1.571429,5,18
3,301.1,67,3.96,1772,1.43,0.0,0.0,0,1,1,0,0,0,7,5,0.714286,4,18
4,269.9,67,2.16,1384,0.00,0.0,0.0,0,1,0,1,0,0,1,2,0.285714,2,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,306.4,51,9.36,2000,0.59,0.0,0.0,0,1,1,0,0,0,7,21,3.000000,6,18
4982,281.4,51,11.88,1977,0.01,0.0,0.0,0,1,0,0,1,0,3,19,2.714286,1,18
4983,295.5,40,9.36,1854,2.64,0.0,0.0,1,1,0,0,0,1,10,3,0.428571,3,18
4984,268.2,59,3.24,2000,0.00,0.0,0.0,0,1,0,1,0,0,1,9,1.285714,2,18
4985,297.3,58,10.44,1211,2.92,0.0,0.0,0,1,0,0,1,0,5,30,4.285714,3,18

In [19]:
dfWS=pd.DataFrame(X,columns=['Wind Speed','Solar Radiation'])              
cols=['Wind Speed','Solar Radiation']                    
for i in cols:
    q75,q25=np.percentile(dfWS.loc[:,i],[75,25])
    IQR = q75-q25
    min=q25-(IQR*1.5)
    max=q75+(IQR*1.5) 
    dfWS.loc[dfWS.loc[:,i]<min,:i]=np.nan
    dfWS.loc[dfWS.loc[:,i]>max,:i]=np.nan

dfWS['Wind Speed']=dfWS['Wind Speed'].fillna(dfWS['Wind Speed'].mean())
dfWS['Solar Radiation']=dfWS['Solar Radiation'].fillna(dfWS['Solar Radiation'].mean())
X['Wind Speed'] = df['Wind Speed'].replace(dfWS['Wind Speed'])
X['Solar Radiation']=df['Solar Radiation'].replace(dfWS['Solar Radiation'])

In [91]:
# df.drop(df[df["Rainfall"] > 2].index, inplace=True)
# df.drop(df[df["Snowfall"] > 4].index, inplace=True)
# df.drop(df[df["Wind Speed"] > 13].index ,inplace=True)

model = RandomForestRegressor(n_estimators= 200, min_samples_split= 2, min_samples_leaf= 1, max_features= 'auto', max_depth= 120, bootstrap= True)
model.fit(x, y)

RandomForestRegressor(max_depth=120, n_estimators=200)

In [65]:
n_estimators = [5,20,50,100,200] # number of trees in the random forest
max_features = ['auto', 'sqrt'] # number of features in consideration at every split
max_depth = [int(x) for x in np.linspace(10, 120, num = 12)] # maximum number of levels allowed in each decision tree
min_samples_split = [2, 6, 10] # minimum sample number to split a node
min_samples_leaf = [1, 3, 4] # minimum sample number that can be stored in a leaf node
bootstrap = [True, False] # method used to sample data points

random_grid = {'n_estimators': n_estimators,

'max_features': max_features,

'max_depth': max_depth,

'min_samples_split': min_samples_split,

'min_samples_leaf': min_samples_leaf,

'bootstrap': bootstrap}
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
from sklearn.model_selection import RandomizedSearchCV
rf_random = RandomizedSearchCV(estimator = rf,param_distributions = random_grid,
               n_iter = 100, cv = 5, verbose=2, random_state=35, n_jobs = -1)

In [66]:
rf_random.fit(x, y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      120],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 3, 4],
                                        'min_samples_split': [2, 6, 10],
                                        'n_estimators': [5, 20, 50, 100, 200]},
                   random_state=35, verbose=2)

In [67]:
print ('Random grid: ', random_grid, '\n')
# print the best parameters
print ('Best Parameters: ', rf_random.best_params_, ' \n')

Random grid:  {'n_estimators': [5, 20, 50, 100, 200], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120], 'min_samples_split': [2, 6, 10], 'min_samples_leaf': [1, 3, 4], 'bootstrap': [True, False]}

Best Parameters:  {'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'auto', 'max_depth': 120, 'bootstrap': True}

In [202]:
from xgboost import XGBRegressor
XGBRegressor()
model1=XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.05, max_delta_step=0,
             max_depth=10, min_child_weight=1, 
             monotone_constraints='()', n_estimators=700, n_jobs=8,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)
model1.fit(x,y)

C:\Users\kalpi\anaconda3\lib\site-packages\xgboost\data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

XGBoostError: [22:33:54] C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/data/data.cc:592: Check failed: labels_.Size() == num_row_ (4986 vs. 3774) : Size of labels must equal to number of rows.

In [140]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
booster=['gbtree','gblinear']
base_score=[0.25,0.5,0.75,1]

## Hyper Parameter Optimization
n_estimators = [200, 400, 600, 700, 900]
max_depth = [2, 3, 5, 10, 15,20]
booster=['gbtree','gblinear']
learning_rate=[0.05,0.1,0.15,0.20]
min_child_weight=[1,2,3,4]

# Define the grid of hyperparameters to search
hyperparameter_grid = {
    'n_estimators': n_estimators,
    'max_depth':max_depth,
    'learning_rate':learning_rate,
    'min_child_weight':min_child_weight,
    'booster':booster,
    'base_score':base_score
    }

# Set up the random search with 4-fold cross validation
random_cv = RandomizedSearchCV(estimator=model1,
            param_distributions=hyperparameter_grid,
            cv=5, n_iter=50,
            scoring = 'neg_mean_absolute_error',n_jobs = -1,
            verbose = 5, 
            return_train_score = True,
            random_state=0)

random_cv.fit(x,y)

random_cv.best_estimator_

Fitting 5 folds for each of 50 candidates, totalling 250 fits

C:\Users\kalpi\anaconda3\lib\site-packages\xgboost\data.py:250: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.05, max_delta_step=0,
             max_depth=10, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=700, n_jobs=8,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [29]:
df1  = pd.read_csv('test.csv')

In [30]:
b=  []
for i in range(0, 3774):
  b.append(0)

df1['Summer'] = b
df1['Winter']  = b
df1['Spring'] = b
df1['Autumn'] =b

for label in seasons:
  df1[label] = np.where(df1['Seasons']==label,1,0)
  df1[['Seasons']+seasons]

df1 = df1.drop('Seasons', axis=1)

In [31]:
from sklearn.preprocessing import LabelEncoder
object_cols=['Holiday','Working Day']
label_encoder = LabelEncoder()
for col in set(object_cols):
    df1[col] = label_encoder.fit_transform(df1[col])
df1['Hour']=df1['Hour'].str.replace(":","")
df1['Hour']=df1['Hour'].astype(int)
df1['Hour'] = df1['Hour'].div(100)

In [33]:
df1

,id,Date,Hour,Hotness,Humidity,Wind Speed,Visibility,Solar Radiation,Rainfall,Snowfall,Holiday,Working Day,Summer,Winter,Spring,Autumn
0,4987,10/06/2018,16.0,297.8,51,5.76,2000,1.17,0.0,0.0,0,1,1,0,0,0
1,4988,21/01/2018,4.0,270.7,47,2.52,984,0.00,0.0,0.0,0,1,0,1,0,0
2,4989,13/12/2017,2.0,262.6,53,6.48,1949,0.00,0.0,0.0,0,1,0,1,0,0
3,4990,07/03/2018,0.0,275.8,45,6.12,1493,0.00,0.0,0.0,0,1,0,0,1,0
4,4991,20/08/2018,22.0,302.0,63,15.12,1776,0.00,0.0,0.0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3769,8756,12/09/2018,8.0,291.2,56,5.40,1994,0.62,0.0,0.0,0,1,0,0,0,1
3770,8757,31/07/2018,16.0,310.0,38,4.32,2000,2.07,0.0,0.0,0,1,1,0,0,0
3771,8758,22/03/2018,15.0,283.7,34,16.20,1850,2.51,0.0,0.0,0,1,0,0,1,0
3772,8759,19/02/2018,10.0,275.6,45,4.32,1230,1.17,0.0,0.0,0,1,0,1,0,0
3773,8760,20/10/2018,9.0,283.4,60,4.68,1326,0.99,0.0,0.0,0,1,0,0,0,1

In [35]:
df1 = df1.drop('id', axis=1)

In [36]:
c=  []
for i in range(0, 3774):
  c.append(0)

df1['Month'] = c
df1['Date1'] = c
df1['Week'] = c
df1['Weekday'] = c
df1['Year'] = c

for i in range(0, 3774):
  df1['Month'][i] = int(df1['Date'][i].split('/')[1])
  df1['Date1'][i] =  int(df1['Date'][i].split('/')[0])
  df1['Week'][i] = int(df1['Date'][i].split('/')[0])/7
  df1['Weekday'][i] = ( weekd[int(df1['Date'][i].split('/')[1]) -1] + int(df1['Date'][i].split('/')[0]) )%7
  df1['Year'][i] = int(df1['Date'][i].split('/')[2])%100

C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\1490904233.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Month'][i] = int(df1['Date'][i].split('/')[1])
C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\1490904233.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Date1'][i] =  int(df1['Date'][i].split('/')[0])
C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\1490904233.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Week'][i] = int(df1['Date'][i].split('/')[0])/7
C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\1490904233.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Weekday'][i] = ( weekd[int(df1['Date'][i].split('/')[1]) -1] + int(df1['Date'][i].split('/')[0]) )%7
C:\Users\kalpi\AppData\Local\Temp\ipykernel_10940\1490904233.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Year'][i] = int(df1['Date'][i].split('/')[2])%100

In [37]:
df1['Month'] = df1['Month'].astype(int)
df1['Date1'] = df1['Date1'].astype(int)
df1['Week'] = df1['Week'].astype(int)
df1['Weekday'] = df1['Weekday'].astype(int)
df1['Year'] = df1['Year'].astype(int)

In [38]:
df1 = df1.drop(['Hour', 'Date'], axis=1)
df1

,Hotness,Humidity,Wind Speed,Visibility,Solar Radiation,Rainfall,Snowfall,Holiday,Working Day,Summer,Winter,Spring,Autumn,Month,Date1,Week,Weekday,Year
0,297.8,51,5.76,2000,1.17,0.0,0.0,0,1,1,0,0,0,6,10,1,0,18
1,270.7,47,2.52,984,0.00,0.0,0.0,0,1,0,1,0,0,1,21,3,0,18
2,262.6,53,6.48,1949,0.00,0.0,0.0,0,1,0,1,0,0,12,13,1,4,17
3,275.8,45,6.12,1493,0.00,0.0,0.0,0,1,0,0,1,0,3,7,1,3,18
4,302.0,63,15.12,1776,0.00,0.0,0.0,0,1,1,0,0,0,8,20,2,1,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3769,291.2,56,5.40,1994,0.62,0.0,0.0,0,1,0,0,0,1,9,12,1,3,18
3770,310.0,38,4.32,2000,2.07,0.0,0.0,0,1,1,0,0,0,7,31,4,2,18
3771,283.7,34,16.20,1850,2.51,0.0,0.0,0,1,0,0,1,0,3,22,3,4,18
3772,275.6,45,4.32,1230,1.17,0.0,0.0,0,1,0,1,0,0,2,19,2,1,18
3773,283.4,60,4.68,1326,0.99,0.0,0.0,0,1,0,0,0,1,10,20,2,6,18

In [39]:
df.drop('Count', axis=1)

,Hotness,Humidity,Wind Speed,Visibility,Solar Radiation,Rainfall,Snowfall,Holiday,Working Day,Summer,Winter,Spring,Autumn,Month,Date1,Week,Weekday,Year
0,300.3,83,5.04,1080,0.00,0.0,0.0,0,1,1,0,0,0,8,5,0.714286,0,18
1,272.6,32,2.16,2000,0.00,0.0,0.0,0,1,0,1,0,0,1,21,3.000000,0,18
2,285.0,83,1.44,321,0.01,0.0,0.0,0,1,0,0,1,0,5,11,1.571429,5,18
3,301.1,67,3.96,1772,1.43,0.0,0.0,0,1,1,0,0,0,7,5,0.714286,4,18
4,269.9,67,2.16,1384,0.00,0.0,0.0,0,1,0,1,0,0,1,2,0.285714,2,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,306.4,51,9.36,2000,0.59,0.0,0.0,0,1,1,0,0,0,7,21,3.000000,6,18
4982,281.4,51,11.88,1977,0.01,0.0,0.0,0,1,0,0,1,0,3,19,2.714286,1,18
4983,295.5,40,9.36,1854,2.64,0.0,0.0,1,1,0,0,0,1,10,3,0.428571,3,18
4984,268.2,59,3.24,2000,0.00,0.0,0.0,0,1,0,1,0,0,1,9,1.285714,2,18
4985,297.3,58,10.44,1211,2.92,0.0,0.0,0,1,0,0,1,0,5,30,4.285714,3,18

In [196]:
X1 = df1
pred =model1.predict(X1)

ValueError: Feature shape mismatch, expected: 19, got 18

In [ ]:
pred = pred.astype(float)
pred
df1  = pd.read_csv('test.csv')
df1['Count'] = pred
df2 = pd.DataFrame()
df2['id'] = df1['id']
df2['Count']=df1['Count']
df2.to_csv("submission.csv", index=None)